#pragma once

struct EvolutionData
{
    bool firstStage;
    bool middleStage;
    bool finalStage;
    bool noEvolutionLine;
    bool notFullyEvolved;
    bool evolvedByLevel;
    bool evolvedByItem;
    bool evolvedByTrade;
    bool evolvedByFriendship;
    bool branchedEvolution;
};

static const EvolutionData evolutionDataBySpecies[1026] =
{
    {false, false, false, false, false, false, false, false, false, false},
    {true, false, false, false, true, false, false, false, false, false}, // #1
    {false, true, false, false, true, true, false, false, false, false}, // #2
    {false, false, true, false, false, true, false, false, false, false}, // #3
    {true, false, false, false, true, false, false, false, false, false}, // #4
    {false, true, false, false, true, true, false, false, false, false}, // #5
    {false, false, true, false, false, true, false, false, false, false}, // #6
    {true, false, false, false, true, false, false, false, false, false}, // #7
    {false, true, false, false, true, true, false, false, false, false}, // #8
    {false, false, true, false, false, true, false, false, false, false}, // #9
    {true, false, false, false, true, false, false, false, false, false}, // #10
    {false, true, false, false, true, true, false, false, false, false}, // #11
    {false, false, true, false, false, true, false, false, false, false}, // #12
    {true, false, false, false, true, false, false, false, false, false}, // #13
    {false, true, false, false, true, true, false, false, false, false}, // #14
    {false, false, true, false, false, true, false, false, false, false}, // #15
    {true, false, false, false, true, false, false, false, false, false}, // #16
    {false, true, false, false, true, true, false, false, false, false}, // #17
    {false, false, true, false, false, true, false, false, false, false}, // #18
    {true, false, false, false, true, false, false, false, false, false}, // #19
    {false, false, true, false, false, true, false, false, false, false}, // #20
    {true, false, false, false, true, false, false, false, false, false}, // #21
    {false, false, true, false, false, true, false, false, false, false}, // #22
    {true, false, false, false, true, false, false, false, false, false}, // #23
    {false, false, true, false, false, true, false, false, false, false}, // #24
    {false, true, false, false, true, true, false, false, true, false}, // #25
    {false, false, true, false, false, false, true, false, false, false}, // #26
    {true, false, false, false, true, false, false, false, false, false}, // #27
    {false, false, true, false, false, true, true, false, false, false}, // #28
    {true, false, false, false, true, false, false, false, false, false}, // #29
    {false, true, false, false, true, true, false, false, false, false}, // #30
    {false, false, true, false, false, false, true, false, false, false}, // #31
    {true, false, false, false, true, false, false, false, false, false}, // #32
    {false, true, false, false, true, true, false, false, false, false}, // #33
    {false, false, true, false, false, false, true, false, false, false}, // #34
    {false, true, false, false, true, true, false, false, true, false}, // #35
    {false, false, true, false, false, false, true, false, false, false}, // #36
    {true, false, false, false, true, false, false, false, false, false}, // #37
    {false, false, true, false, false, false, true, false, false, false}, // #38
    {false, true, false, false, true, true, false, false, true, false}, // #39
    {false, false, true, false, false, false, true, false, false, false}, // #40
    {true, false, false, false, true, false, false, false, false, false}, // #41
    {false, true, false, false, true, true, false, false, false, false}, // #42
    {true, false, false, false, true, false, false, false, false, false}, // #43
    {false, true, false, false, true, true, false, false, false, true}, // #44
    {false, false, true, false, false, false, true, false, false, false}, // #45
    {true, false, false, false, true, false, false, false, false, false}, // #46
    {false, false, true, false, false, true, false, false, false, false}, // #47
    {true, false, false, false, true, false, false, false, false, false}, // #48
    {false, false, true, false, false, true, false, false, false, false}, // #49
    {true, false, false, false, true, false, false, false, false, false}, // #50
    {false, false, true, false, false, true, false, false, false, false}, // #51
    {true, false, false, false, true, false, false, false, false, true}, // #52
    {false, false, true, false, false, true, false, false, true, false}, // #53
    {true, false, false, false, true, false, false, false, false, false}, // #54
    {false, false, true, false, false, true, false, false, false, false}, // #55
    {true, false, false, false, true, false, false, false, false, false}, // #56
    {false, true, false, false, true, true, false, false, false, false}, // #57
    {true, false, false, false, true, false, false, false, false, false}, // #58
    {false, false, true, false, false, false, true, false, false, false}, // #59
    {true, false, false, false, true, false, false, false, false, false}, // #60
    {false, true, false, false, true, true, false, false, false, true}, // #61
    {false, false, true, false, false, false, true, false, false, false}, // #62
    {true, false, false, false, true, false, false, false, false, false}, // #63
    {false, true, false, false, true, true, false, false, false, false}, // #64
    {false, false, true, false, false, false, true, true, false, false}, // #65
    {true, false, false, false, true, false, false, false, false, false}, // #66
    {false, true, false, false, true, true, false, false, false, false}, // #67
    {false, false, true, false, false, false, true, true, false, false}, // #68
    {true, false, false, false, true, false, false, false, false, false}, // #69
    {false, true, false, false, true, true, false, false, false, false}, // #70
    {false, false, true, false, false, false, true, false, false, false}, // #71
    {true, false, false, false, true, false, false, false, false, false}, // #72
    {false, false, true, false, false, true, false, false, false, false}, // #73
    {true, false, false, false, true, false, false, false, false, false}, // #74
    {false, true, false, false, true, true, false, false, false, false}, // #75
    {false, false, true, false, false, false, true, true, false, false}, // #76
    {true, false, false, false, true, false, false, false, false, false}, // #77
    {false, false, true, false, false, true, false, false, false, false}, // #78
    {true, false, false, false, true, false, false, false, false, true}, // #79
    {false, false, true, false, false, true, true, false, false, false}, // #80
    {true, false, false, false, true, false, false, false, false, false}, // #81
    {false, true, false, false, true, true, false, false, false, false}, // #82
    {true, false, false, false, true, false, false, false, false, false}, // #83
    {true, false, false, false, true, false, false, false, false, false}, // #84
    {false, false, true, false, false, true, false, false, false, false}, // #85
    {true, false, false, false, true, false, false, false, false, false}, // #86
    {false, false, true, false, false, true, false, false, false, false}, // #87
    {true, false, false, false, true, false, false, false, false, false}, // #88
    {false, false, true, false, false, true, false, false, false, false}, // #89
    {true, false, false, false, true, false, false, false, false, false}, // #90
    {false, false, true, false, false, false, true, false, false, false}, // #91
    {true, false, false, false, true, false, false, false, false, false}, // #92
    {false, true, false, false, true, true, false, false, false, false}, // #93
    {false, false, true, false, false, false, true, true, false, false}, // #94
    {true, false, false, false, true, false, false, false, false, false}, // #95
    {true, false, false, false, true, false, false, false, false, false}, // #96
    {false, false, true, false, false, true, false, false, false, false}, // #97
    {true, false, false, false, true, false, false, false, false, false}, // #98
    {false, false, true, false, false, true, false, false, false, false}, // #99
    {true, false, false, false, true, false, false, false, false, false}, // #100
    {false, false, true, false, false, true, true, false, false, false}, // #101
    {true, false, false, false, true, false, false, false, false, false}, // #102
    {false, false, true, false, false, false, true, false, false, false}, // #103
    {true, false, false, false, true, false, false, false, false, false}, // #104
    {false, false, true, false, false, true, false, false, false, false}, // #105
    {false, false, true, false, false, true, false, false, false, false}, // #106
    {false, false, true, false, false, true, false, false, false, false}, // #107
    {true, false, false, false, true, false, false, false, false, false}, // #108
    {true, false, false, false, true, false, false, false, false, false}, // #109
    {false, false, true, false, false, true, false, false, false, false}, // #110
    {true, false, false, false, true, false, false, false, false, false}, // #111
    {false, true, false, false, true, true, false, false, false, false}, // #112
    {false, true, false, false, true, true, true, false, false, false}, // #113
    {true, false, false, false, true, false, false, false, false, false}, // #114
    {false, false, false, true, false, false, false, false, false, false}, // #115
    {true, false, false, false, true, false, false, false, false, false}, // #116
    {false, true, false, false, true, true, false, false, false, false}, // #117
    {true, false, false, false, true, false, false, false, false, false}, // #118
    {false, false, true, false, false, true, false, false, false, false}, // #119
    {true, false, false, false, true, false, false, false, false, false}, // #120
    {false, false, true, false, false, false, true, false, false, false}, // #121
    {false, true, false, false, true, true, false, false, false, false}, // #122
    {true, false, false, false, true, false, false, false, false, true}, // #123
    {false, false, true, false, false, true, false, false, false, false}, // #124
    {false, true, false, false, true, true, false, false, false, false}, // #125
    {false, true, false, false, true, true, false, false, false, false}, // #126
    {false, false, false, true, false, false, false, false, false, false}, // #127
    {false, false, false, true, false, false, false, false, false, false}, // #128
    {true, false, false, false, true, false, false, false, false, false}, // #129
    {false, false, true, false, false, true, false, false, false, false}, // #130
    {false, false, false, true, false, false, false, false, false, false}, // #131
    {false, false, false, true, false, false, false, false, false, false}, // #132
    {true, false, false, false, true, false, false, false, false, true}, // #133
    {false, false, true, false, false, false, true, false, false, false}, // #134
    {false, false, true, false, false, false, true, false, false, false}, // #135
    {false, false, true, false, false, false, true, false, false, false}, // #136
    {true, false, false, false, true, false, false, false, false, false}, // #137
    {true, false, false, false, true, false, false, false, false, false}, // #138
    {false, false, true, false, false, true, false, false, false, false}, // #139
    {true, false, false, false, true, false, false, false, false, false}, // #140
    {false, false, true, false, false, true, false, false, false, false}, // #141
    {false, false, false, true, false, false, false, false, false, false}, // #142
    {false, false, true, false, false, true, false, false, true, false}, // #143
    {false, false, false, true, false, false, false, false, false, false}, // #144
    {false, false, false, true, false, false, false, false, false, false}, // #145
    {false, false, false, true, false, false, false, false, false, false}, // #146
    {true, false, false, false, true, false, false, false, false, false}, // #147
    {false, true, false, false, true, true, false, false, false, false}, // #148
    {false, false, true, false, false, true, false, false, false, false}, // #149
    {false, false, false, true, false, false, false, false, false, false}, // #150
    {false, false, false, true, false, false, false, false, false, false}, // #151
    {true, false, false, false, true, false, false, false, false, false}, // #152
    {false, true, false, false, true, true, false, false, false, false}, // #153
    {false, false, true, false, false, true, false, false, false, false}, // #154
    {true, false, false, false, true, false, false, false, false, false}, // #155
    {false, true, false, false, true, true, false, false, false, false}, // #156
    {false, false, true, false, false, true, false, false, false, false}, // #157
    {true, false, false, false, true, false, false, false, false, false}, // #158
    {false, true, false, false, true, true, false, false, false, false}, // #159
    {false, false, true, false, false, true, false, false, false, false}, // #160
    {true, false, false, false, true, false, false, false, false, false}, // #161
    {false, false, true, false, false, true, false, false, false, false}, // #162
    {true, false, false, false, true, false, false, false, false, false}, // #163
    {false, false, true, false, false, true, false, false, false, false}, // #164
    {true, false, false, false, true, false, false, false, false, false}, // #165
    {false, false, true, false, false, true, false, false, false, false}, // #166
    {true, false, false, false, true, false, false, false, false, false}, // #167
    {false, false, true, false, false, true, false, false, false, false}, // #168
    {false, false, true, false, false, true, false, false, true, false}, // #169
    {true, false, false, false, true, false, false, false, false, false}, // #170
    {false, false, true, false, false, true, false, false, false, false}, // #171
    {true, false, false, false, true, false, false, false, false, false}, // #172
    {true, false, false, false, true, false, false, false, false, false}, // #173
    {true, false, false, false, true, false, false, false, false, false}, // #174
    {true, false, false, false, true, false, false, false, false, false}, // #175
    {false, true, false, false, true, true, false, false, true, false}, // #176
    {true, false, false, false, true, false, false, false, false, false}, // #177
    {false, false, true, false, false, true, false, false, false, false}, // #178
    {true, false, false, false, true, false, false, false, false, false}, // #179
    {false, true, false, false, true, true, false, false, false, false}, // #180
    {false, false, true, false, false, true, false, false, false, false}, // #181
    {false, false, true, false, false, false, true, false, false, false}, // #182
    {false, true, false, false, true, true, false, false, true, false}, // #183
    {false, false, true, false, false, true, false, false, false, false}, // #184
    {false, false, true, false, false, true, false, false, false, false}, // #185
    {false, false, true, false, false, false, true, true, false, false}, // #186
    {true, false, false, false, true, false, false, false, false, false}, // #187
    {false, true, false, false, true, true, false, false, false, false}, // #188
    {false, false, true, false, false, true, false, false, false, false}, // #189
    {true, false, false, false, true, false, false, false, false, false}, // #190
    {true, false, false, false, true, false, false, false, false, false}, // #191
    {false, false, true, false, false, false, true, false, false, false}, // #192
    {true, false, false, false, true, false, false, false, false, false}, // #193
    {true, false, false, false, true, false, false, false, false, true}, // #194
    {false, false, true, false, false, true, false, false, false, false}, // #195
    {false, false, true, false, false, true, false, false, true, false}, // #196
    {false, false, true, false, false, true, false, false, true, false}, // #197
    {true, false, false, false, true, false, false, false, false, false}, // #198
    {false, false, true, false, false, false, true, true, false, false}, // #199
    {true, false, false, false, true, false, false, false, false, false}, // #200
    {false, false, false, true, false, false, false, false, false, false}, // #201
    {false, false, true, false, false, true, false, false, false, false}, // #202
    {true, false, false, false, true, false, false, false, false, false}, // #203
    {true, false, false, false, true, false, false, false, false, false}, // #204
    {false, false, true, false, false, true, false, false, false, false}, // #205
    {true, false, false, false, true, false, false, false, false, false}, // #206
    {true, false, false, false, true, false, false, false, false, false}, // #207
    {false, false, true, false, false, false, true, true, false, false}, // #208
    {true, false, false, false, true, false, false, false, false, false}, // #209
    {false, false, true, false, false, true, false, false, false, false}, // #210
    {true, false, false, false, true, false, false, false, false, false}, // #211
    {false, false, true, false, false, false, true, true, false, false}, // #212
    {false, false, false, true, false, false, false, false, false, false}, // #213
    {false, false, false, true, false, false, false, false, false, false}, // #214
    {true, false, false, false, true, false, false, false, false, true}, // #215
    {true, false, false, false, true, false, false, false, false, false}, // #216
    {false, true, false, false, true, true, false, false, false, false}, // #217
    {true, false, false, false, true, false, false, false, false, false}, // #218
    {false, false, true, false, false, true, false, false, false, false}, // #219
    {true, false, false, false, true, false, false, false, false, false}, // #220
    {false, true, false, false, true, true, false, false, false, false}, // #221
    {true, false, false, false, true, false, false, false, false, false}, // #222
    {true, false, false, false, true, false, false, false, false, false}, // #223
    {false, false, true, false, false, true, false, false, false, false}, // #224
    {false, false, false, true, false, false, false, false, false, false}, // #225
    {false, false, true, false, false, true, false, false, false, false}, // #226
    {false, false, false, true, false, false, false, false, false, false}, // #227
    {true, false, false, false, true, false, false, false, false, false}, // #228
    {false, false, true, false, false, true, false, false, false, false}, // #229
    {false, false, true, false, false, false, true, true, false, false}, // #230
    {true, false, false, false, true, false, false, false, false, false}, // #231
    {false, false, true, false, false, true, false, false, false, false}, // #232
    {false, true, false, false, true, false, true, true, false, false}, // #233
    {true, false, false, false, true, false, false, false, false, false}, // #234
    {false, false, false, true, false, false, false, false, false, false}, // #235
    {true, false, false, false, true, false, false, false, false, true}, // #236
    {false, false, true, false, false, true, false, false, false, false}, // #237
    {true, false, false, false, true, false, false, false, false, false}, // #238
    {true, false, false, false, true, false, false, false, false, false}, // #239
    {true, false, false, false, true, false, false, false, false, false}, // #240
    {false, false, false, true, false, false, false, false, false, false}, // #241
    {false, false, true, false, false, true, false, false, true, false}, // #242
    {false, false, false, true, false, false, false, false, false, false}, // #243
    {false, false, false, true, false, false, false, false, false, false}, // #244
    {false, false, false, true, false, false, false, false, false, false}, // #245
    {true, false, false, false, true, false, false, false, false, false}, // #246
    {false, true, false, false, true, true, false, false, false, false}, // #247
    {false, false, true, false, false, true, false, false, false, false}, // #248
    {false, false, false, true, false, false, false, false, false, false}, // #249
    {false, false, false, true, false, false, false, false, false, false}, // #250
    {false, false, false, true, false, false, false, false, false, false}, // #251
    {true, false, false, false, true, false, false, false, false, false}, // #252
    {false, true, false, false, true, true, false, false, false, false}, // #253
    {false, false, true, false, false, true, false, false, false, false}, // #254
    {true, false, false, false, true, false, false, false, false, false}, // #255
    {false, true, false, false, true, true, false, false, false, false}, // #256
    {false, false, true, false, false, true, false, false, false, false}, // #257
    {true, false, false, false, true, false, false, false, false, false}, // #258
    {false, true, false, false, true, true, false, false, false, false}, // #259
    {false, false, true, false, false, true, false, false, false, false}, // #260
    {true, false, false, false, true, false, false, false, false, false}, // #261
    {false, false, true, false, false, true, false, false, false, false}, // #262
    {true, false, false, false, true, false, false, false, false, false}, // #263
    {false, true, false, false, true, true, false, false, false, false}, // #264
    {true, false, false, false, true, false, false, false, false, true}, // #265
    {false, true, false, false, true, true, false, false, false, false}, // #266
    {false, false, true, false, false, true, false, false, false, false}, // #267
    {false, true, false, false, true, true, false, false, false, false}, // #268
    {false, false, true, false, false, true, false, false, false, false}, // #269
    {true, false, false, false, true, false, false, false, false, false}, // #270
    {false, true, false, false, true, true, false, false, false, false}, // #271
    {false, false, true, false, false, false, true, false, false, false}, // #272
    {true, false, false, false, true, false, false, false, false, false}, // #273
    {false, true, false, false, true, true, false, false, false, false}, // #274
    {false, false, true, false, false, false, true, false, false, false}, // #275
    {true, false, false, false, true, false, false, false, false, false}, // #276
    {false, false, true, false, false, true, false, false, false, false}, // #277
    {true, false, false, false, true, false, false, false, false, false}, // #278
    {false, false, true, false, false, true, false, false, false, false}, // #279
    {true, false, false, false, true, false, false, false, false, false}, // #280
    {false, true, false, false, true, true, false, false, false, true}, // #281
    {false, false, true, false, false, true, false, false, false, false}, // #282
    {true, false, false, false, true, false, false, false, false, false}, // #283
    {false, false, true, false, false, true, false, false, false, false}, // #284
    {true, false, false, false, true, false, false, false, false, false}, // #285
    {false, false, true, false, false, true, false, false, false, false}, // #286
    {true, false, false, false, true, false, false, false, false, false}, // #287
    {false, true, false, false, true, true, false, false, false, false}, // #288
    {false, false, true, false, false, true, false, false, false, false}, // #289
    {true, false, false, false, true, false, false, false, false, true}, // #290
    {false, false, true, false, false, true, false, false, false, false}, // #291
    {false, false, true, false, false, false, false, false, false, false}, // #292
    {true, false, false, false, true, false, false, false, false, false}, // #293
    {false, true, false, false, true, true, false, false, false, false}, // #294
    {false, false, true, false, false, true, false, false, false, false}, // #295
    {true, false, false, false, true, false, false, false, false, false}, // #296
    {false, false, true, false, false, true, false, false, false, false}, // #297
    {true, false, false, false, true, false, false, false, false, false}, // #298
    {true, false, false, false, true, false, false, false, false, false}, // #299
    {true, false, false, false, true, false, false, false, false, false}, // #300
    {false, false, true, false, false, false, true, false, false, false}, // #301
    {false, false, false, true, false, false, false, false, false, false}, // #302
    {false, false, false, true, false, false, false, false, false, false}, // #303
    {true, false, false, false, true, false, false, false, false, false}, // #304
    {false, true, false, false, true, true, false, false, false, false}, // #305
    {false, false, true, false, false, true, false, false, false, false}, // #306
    {true, false, false, false, true, false, false, false, false, false}, // #307
    {false, false, true, false, false, true, false, false, false, false}, // #308
    {true, false, false, false, true, false, false, false, false, false}, // #309
    {false, false, true, false, false, true, false, false, false, false}, // #310
    {false, false, false, true, false, false, false, false, false, false}, // #311
    {false, false, false, true, false, false, false, false, false, false}, // #312
    {false, false, false, true, false, false, false, false, false, false}, // #313
    {false, false, false, true, false, false, false, false, false, false}, // #314
    {false, true, false, false, true, true, false, false, true, false}, // #315
    {true, false, false, false, true, false, false, false, false, false}, // #316
    {false, false, true, false, false, true, false, false, false, false}, // #317
    {true, false, false, false, true, false, false, false, false, false}, // #318
    {false, false, true, false, false, true, false, false, false, false}, // #319
    {true, false, false, false, true, false, false, false, false, false}, // #320
    {false, false, true, false, false, true, false, false, false, false}, // #321
    {true, false, false, false, true, false, false, false, false, false}, // #322
    {false, false, true, false, false, true, false, false, false, false}, // #323
    {false, false, false, true, false, false, false, false, false, false}, // #324
    {true, false, false, false, true, false, false, false, false, false}, // #325
    {false, false, true, false, false, true, false, false, false, false}, // #326
    {false, false, false, true, false, false, false, false, false, false}, // #327
    {true, false, false, false, true, false, false, false, false, false}, // #328
    {false, true, false, false, true, true, false, false, false, false}, // #329
    {false, false, true, false, false, true, false, false, false, false}, // #330
    {true, false, false, false, true, false, false, false, false, false}, // #331
    {false, false, true, false, false, true, false, false, false, false}, // #332
    {true, false, false, false, true, false, false, false, false, false}, // #333
    {false, false, true, false, false, true, false, false, false, false}, // #334
    {false, false, false, true, false, false, false, false, false, false}, // #335
    {false, false, false, true, false, false, false, false, false, false}, // #336
    {false, false, false, true, false, false, false, false, false, false}, // #337
    {false, false, false, true, false, false, false, false, false, false}, // #338
    {true, false, false, false, true, false, false, false, false, false}, // #339
    {false, false, true, false, false, true, false, false, false, false}, // #340
    {true, false, false, false, true, false, false, false, false, false}, // #341
    {false, false, true, false, false, true, false, false, false, false}, // #342
    {true, false, false, false, true, false, false, false, false, false}, // #343
    {false, false, true, false, false, true, false, false, false, false}, // #344
    {true, false, false, false, true, false, false, false, false, false}, // #345
    {false, false, true, false, false, true, false, false, false, false}, // #346
    {true, false, false, false, true, false, false, false, false, false}, // #347
    {false, false, true, false, false, true, false, false, false, false}, // #348
    {true, false, false, false, true, false, false, false, false, false}, // #349
    {false, false, true, false, false, true, true, true, false, false}, // #350
    {false, false, false, true, false, false, false, false, false, false}, // #351
    {false, false, false, true, false, false, false, false, false, false}, // #352
    {true, false, false, false, true, false, false, false, false, false}, // #353
    {false, false, true, false, false, true, false, false, false, false}, // #354
    {true, false, false, false, true, false, false, false, false, false}, // #355
    {false, true, false, false, true, true, false, false, false, false}, // #356
    {false, false, false, true, false, false, false, false, false, false}, // #357
    {false, false, true, false, false, true, false, false, true, false}, // #358
    {false, false, false, true, false, false, false, false, false, false}, // #359
    {true, false, false, false, true, false, false, false, false, false}, // #360
    {true, false, false, false, true, false, false, false, false, true}, // #361
    {false, false, true, false, false, true, false, false, false, false}, // #362
    {true, false, false, false, true, false, false, false, false, false}, // #363
    {false, true, false, false, true, true, false, false, false, false}, // #364
    {false, false, true, false, false, true, false, false, false, false}, // #365
    {true, false, false, false, true, false, false, false, false, true}, // #366
    {false, false, true, false, false, false, true, true, false, false}, // #367
    {false, false, true, false, false, false, true, true, false, false}, // #368
    {false, false, false, true, false, false, false, false, false, false}, // #369
    {false, false, false, true, false, false, false, false, false, false}, // #370
    {true, false, false, false, true, false, false, false, false, false}, // #371
    {false, true, false, false, true, true, false, false, false, false}, // #372
    {false, false, true, false, false, true, false, false, false, false}, // #373
    {true, false, false, false, true, false, false, false, false, false}, // #374
    {false, true, false, false, true, true, false, false, false, false}, // #375
    {false, false, true, false, false, true, false, false, false, false}, // #376
    {false, false, false, true, false, false, false, false, false, false}, // #377
    {false, false, false, true, false, false, false, false, false, false}, // #378
    {false, false, false, true, false, false, false, false, false, false}, // #379
    {false, false, false, true, false, false, false, false, false, false}, // #380
    {false, false, false, true, false, false, false, false, false, false}, // #381
    {false, false, false, true, false, false, false, false, false, false}, // #382
    {false, false, false, true, false, false, false, false, false, false}, // #383
    {false, false, false, true, false, false, false, false, false, false}, // #384
    {false, false, false, true, false, false, false, false, false, false}, // #385
    {false, false, false, true, false, false, false, false, false, false}, // #386
    {true, false, false, false, true, false, false, false, false, false}, // #387
    {false, true, false, false, true, true, false, false, false, false}, // #388
    {false, false, true, false, false, true, false, false, false, false}, // #389
    {true, false, false, false, true, false, false, false, false, false}, // #390
    {false, true, false, false, true, true, false, false, false, false}, // #391
    {false, false, true, false, false, true, false, false, false, false}, // #392
    {true, false, false, false, true, false, false, false, false, false}, // #393
    {false, true, false, false, true, true, false, false, false, false}, // #394
    {false, false, true, false, false, true, false, false, false, false}, // #395
    {true, false, false, false, true, false, false, false, false, false}, // #396
    {false, true, false, false, true, true, false, false, false, false}, // #397
    {false, false, true, false, false, true, false, false, false, false}, // #398
    {true, false, false, false, true, false, false, false, false, false}, // #399
    {false, false, true, false, false, true, false, false, false, false}, // #400
    {true, false, false, false, true, false, false, false, false, false}, // #401
    {false, false, true, false, false, true, false, false, false, false}, // #402
    {true, false, false, false, true, false, false, false, false, false}, // #403
    {false, true, false, false, true, true, false, false, false, false}, // #404
    {false, false, true, false, false, true, false, false, false, false}, // #405
    {true, false, false, false, true, false, false, false, false, false}, // #406
    {false, false, true, false, false, false, true, false, false, false}, // #407
    {true, false, false, false, true, false, false, false, false, false}, // #408
    {false, false, true, false, false, true, false, false, false, false}, // #409
    {true, false, false, false, true, false, false, false, false, false}, // #410
    {false, false, true, false, false, true, false, false, false, false}, // #411
    {true, false, false, false, true, false, false, false, false, true}, // #412
    {false, false, true, false, false, true, false, false, false, false}, // #413
    {false, false, true, false, false, true, false, false, false, false}, // #414
    {true, false, false, false, true, false, false, false, false, false}, // #415
    {false, false, true, false, false, true, false, false, false, false}, // #416
    {false, false, false, true, false, false, false, false, false, false}, // #417
    {true, false, false, false, true, false, false, false, false, false}, // #418
    {false, false, true, false, false, true, false, false, false, false}, // #419
    {true, false, false, false, true, false, false, false, false, false}, // #420
    {false, false, true, false, false, true, false, false, false, false}, // #421
    {true, false, false, false, true, false, false, false, false, false}, // #422
    {false, false, true, false, false, true, false, false, false, false}, // #423
    {false, false, true, false, false, true, false, false, false, false}, // #424
    {true, false, false, false, true, false, false, false, false, false}, // #425
    {false, false, true, false, false, true, false, false, false, false}, // #426
    {true, false, false, false, true, false, false, false, false, false}, // #427
    {false, false, true, false, false, true, false, false, true, false}, // #428
    {false, false, true, false, false, false, true, false, false, false}, // #429
    {false, false, true, false, false, false, true, false, false, false}, // #430
    {true, false, false, false, true, false, false, false, false, false}, // #431
    {false, false, true, false, false, true, false, false, false, false}, // #432
    {true, false, false, false, true, false, false, false, false, false}, // #433
    {true, false, false, false, true, false, false, false, false, false}, // #434
    {false, false, true, false, false, true, false, false, false, false}, // #435
    {true, false, false, false, true, false, false, false, false, false}, // #436
    {false, false, true, false, false, true, false, false, false, false}, // #437
    {true, false, false, false, true, false, false, false, false, false}, // #438
    {true, false, false, false, true, false, false, false, false, false}, // #439
    {true, false, false, false, true, false, false, false, false, false}, // #440
    {false, false, false, true, false, false, false, false, false, false}, // #441
    {false, false, false, true, false, false, false, false, false, false}, // #442
    {true, false, false, false, true, false, false, false, false, false}, // #443
    {false, true, false, false, true, true, false, false, false, false}, // #444
    {false, false, true, false, false, true, false, false, false, false}, // #445
    {true, false, false, false, true, false, false, false, false, false}, // #446
    {true, false, false, false, true, false, false, false, false, false}, // #447
    {false, false, true, false, false, true, false, false, true, false}, // #448
    {true, false, false, false, true, false, false, false, false, false}, // #449
    {false, false, true, false, false, true, false, false, false, false}, // #450
    {true, false, false, false, true, false, false, false, false, false}, // #451
    {false, false, true, false, false, true, false, false, false, false}, // #452
    {true, false, false, false, true, false, false, false, false, false}, // #453
    {false, false, true, false, false, true, false, false, false, false}, // #454
    {false, false, false, true, false, false, false, false, false, false}, // #455
    {true, false, false, false, true, false, false, false, false, false}, // #456
    {false, false, true, false, false, true, false, false, false, false}, // #457
    {true, false, false, false, true, false, false, false, false, false}, // #458
    {true, false, false, false, true, false, false, false, false, false}, // #459
    {false, false, true, false, false, true, false, false, false, false}, // #460
    {false, false, true, false, false, true, true, false, false, false}, // #461
    {false, false, true, false, false, true, true, false, false, false}, // #462
    {false, false, true, false, false, true, false, false, false, false}, // #463
    {false, false, true, false, false, false, true, true, false, false}, // #464
    {false, false, true, false, false, true, false, false, false, false}, // #465
    {false, false, true, false, false, false, true, true, false, false}, // #466
    {false, false, true, false, false, false, true, true, false, false}, // #467
    {false, false, true, false, false, false, true, false, false, false}, // #468
    {false, false, true, false, false, true, false, false, false, false}, // #469
    {false, false, true, false, false, true, true, false, false, false}, // #470
    {false, false, true, false, false, true, true, false, false, false}, // #471
    {false, false, true, false, false, true, true, false, false, false}, // #472
    {false, false, true, false, false, true, false, false, false, false}, // #473
    {false, false, true, false, false, false, true, true, false, false}, // #474
    {false, false, true, false, false, false, true, false, false, false}, // #475
    {false, false, true, false, false, true, true, false, false, false}, // #476
    {false, false, true, false, false, false, true, true, false, false}, // #477
    {false, false, true, false, false, false, true, false, false, false}, // #478
    {false, false, false, true, false, false, false, false, false, false}, // #479
    {false, false, false, true, false, false, false, false, false, false}, // #480
    {false, false, false, true, false, false, false, false, false, false}, // #481
    {false, false, false, true, false, false, false, false, false, false}, // #482
    {false, false, false, true, false, false, false, false, false, false}, // #483
    {false, false, false, true, false, false, false, false, false, false}, // #484
    {false, false, false, true, false, false, false, false, false, false}, // #485
    {false, false, false, true, false, false, false, false, false, false}, // #486
    {false, false, false, true, false, false, false, false, false, false}, // #487
    {false, false, false, true, false, false, false, false, false, false}, // #488
    {true, false, false, false, true, false, false, false, false, false}, // #489
    {false, false, true, false, false, false, false, false, false, false}, // #490
    {false, false, false, true, false, false, false, false, false, false}, // #491
    {false, false, false, true, false, false, false, false, false, false}, // #492
    {false, false, false, true, false, false, false, false, false, false}, // #493
    {false, false, false, true, false, false, false, false, false, false}, // #494
    {true, false, false, false, true, false, false, false, false, false}, // #495
    {false, true, false, false, true, true, false, false, false, false}, // #496
    {false, false, true, false, false, true, false, false, false, false}, // #497
    {true, false, false, false, true, false, false, false, false, false}, // #498
    {false, true, false, false, true, true, false, false, false, false}, // #499
    {false, false, true, false, false, true, false, false, false, false}, // #500
    {true, false, false, false, true, false, false, false, false, false}, // #501
    {false, true, false, false, true, true, false, false, false, false}, // #502
    {false, false, true, false, false, true, false, false, false, false}, // #503
    {true, false, false, false, true, false, false, false, false, false}, // #504
    {false, false, true, false, false, true, false, false, false, false}, // #505
    {true, false, false, false, true, false, false, false, false, false}, // #506
    {false, true, false, false, true, true, false, false, false, false}, // #507
    {false, false, true, false, false, true, false, false, false, false}, // #508
    {true, false, false, false, true, false, false, false, false, false}, // #509
    {false, false, true, false, false, true, false, false, false, false}, // #510
    {true, false, false, false, true, false, false, false, false, false}, // #511
    {false, false, true, false, false, false, true, false, false, false}, // #512
    {true, false, false, false, true, false, false, false, false, false}, // #513
    {false, false, true, false, false, false, true, false, false, false}, // #514
    {true, false, false, false, true, false, false, false, false, false}, // #515
    {false, false, true, false, false, false, true, false, false, false}, // #516
    {true, false, false, false, true, false, false, false, false, false}, // #517
    {false, false, true, false, false, false, true, false, false, false}, // #518
    {true, false, false, false, true, false, false, false, false, false}, // #519
    {false, true, false, false, true, true, false, false, false, false}, // #520
    {false, false, true, false, false, true, false, false, false, false}, // #521
    {true, false, false, false, true, false, false, false, false, false}, // #522
    {false, false, true, false, false, true, false, false, false, false}, // #523
    {true, false, false, false, true, false, false, false, false, false}, // #524
    {false, true, false, false, true, true, false, false, false, false}, // #525
    {false, false, true, false, false, false, false, true, false, false}, // #526
    {true, false, false, false, true, false, false, false, false, false}, // #527
    {false, false, true, false, false, true, false, false, true, false}, // #528
    {true, false, false, false, true, false, false, false, false, false}, // #529
    {false, false, true, false, false, true, false, false, false, false}, // #530
    {false, false, false, true, false, false, false, false, false, false}, // #531
    {true, false, false, false, true, false, false, false, false, false}, // #532
    {false, true, false, false, true, true, false, false, false, false}, // #533
    {false, false, true, false, false, false, false, true, false, false}, // #534
    {true, false, false, false, true, false, false, false, false, false}, // #535
    {false, true, false, false, true, true, false, false, false, false}, // #536
    {false, false, true, false, false, true, false, false, false, false}, // #537
    {false, false, false, true, false, false, false, false, false, false}, // #538
    {false, false, false, true, false, false, false, false, false, false}, // #539
    {true, false, false, false, true, false, false, false, false, false}, // #540
    {false, true, false, false, true, true, false, false, false, false}, // #541
    {false, false, true, false, false, true, false, false, true, false}, // #542
    {true, false, false, false, true, false, false, false, false, false}, // #543
    {false, true, false, false, true, true, false, false, false, false}, // #544
    {false, false, true, false, false, true, false, false, false, false}, // #545
    {true, false, false, false, true, false, false, false, false, false}, // #546
    {false, false, true, false, false, false, true, false, false, false}, // #547
    {true, false, false, false, true, false, false, false, false, false}, // #548
    {false, false, true, false, false, false, true, false, false, false}, // #549
    {true, false, false, false, true, false, false, false, false, false}, // #550
    {true, false, false, false, true, false, false, false, false, false}, // #551
    {false, true, false, false, true, true, false, false, false, false}, // #552
    {false, false, true, false, false, true, false, false, false, false}, // #553
    {true, false, false, false, true, false, false, false, false, false}, // #554
    {false, false, true, false, false, true, true, false, false, false}, // #555
    {false, false, false, true, false, false, false, false, false, false}, // #556
    {true, false, false, false, true, false, false, false, false, false}, // #557
    {false, false, true, false, false, true, false, false, false, false}, // #558
    {true, false, false, false, true, false, false, false, false, false}, // #559
    {false, false, true, false, false, true, false, false, false, false}, // #560
    {false, false, false, true, false, false, false, false, false, false}, // #561
    {true, false, false, false, true, false, false, false, false, true}, // #562
    {false, false, true, false, false, true, false, false, false, false}, // #563
    {true, false, false, false, true, false, false, false, false, false}, // #564
    {false, false, true, false, false, true, false, false, false, false}, // #565
    {true, false, false, false, true, false, false, false, false, false}, // #566
    {false, false, true, false, false, true, false, false, false, false}, // #567
    {true, false, false, false, true, false, false, false, false, false}, // #568
    {false, false, true, false, false, true, false, false, false, false}, // #569
    {true, false, false, false, true, false, false, false, false, false}, // #570
    {false, false, true, false, false, true, false, false, false, false}, // #571
    {true, false, false, false, true, false, false, false, false, false}, // #572
    {false, false, true, false, false, false, true, false, false, false}, // #573
    {true, false, false, false, true, false, false, false, false, false}, // #574
    {false, true, false, false, true, true, false, false, false, false}, // #575
    {false, false, true, false, false, true, false, false, false, false}, // #576
    {true, false, false, false, true, false, false, false, false, false}, // #577
    {false, true, false, false, true, true, false, false, false, false}, // #578
    {false, false, true, false, false, true, false, false, false, false}, // #579
    {true, false, false, false, true, false, false, false, false, false}, // #580
    {false, false, true, false, false, true, false, false, false, false}, // #581
    {true, false, false, false, true, false, false, false, false, false}, // #582
    {false, true, false, false, true, true, false, false, false, false}, // #583
    {false, false, true, false, false, true, false, false, false, false}, // #584
    {true, false, false, false, true, false, false, false, false, false}, // #585
    {false, false, true, false, false, true, false, false, false, false}, // #586
    {false, false, false, true, false, false, false, false, false, false}, // #587
    {true, false, false, false, true, false, false, false, false, false}, // #588
    {false, false, true, false, false, false, false, true, false, false}, // #589
    {true, false, false, false, true, false, false, false, false, false}, // #590
    {false, false, true, false, false, true, false, false, false, false}, // #591
    {true, false, false, false, true, false, false, false, false, false}, // #592
    {false, false, true, false, false, true, false, false, false, false}, // #593
    {false, false, false, true, false, false, false, false, false, false}, // #594
    {true, false, false, false, true, false, false, false, false, false}, // #595
    {false, false, true, false, false, true, false, false, false, false}, // #596
    {true, false, false, false, true, false, false, false, false, false}, // #597
    {false, false, true, false, false, true, false, false, false, false}, // #598
    {true, false, false, false, true, false, false, false, false, false}, // #599
    {false, true, false, false, true, true, false, false, false, false}, // #600
    {false, false, true, false, false, true, false, false, false, false}, // #601
    {true, false, false, false, true, false, false, false, false, false}, // #602
    {false, true, false, false, true, true, false, false, false, false}, // #603
    {false, false, true, false, false, false, true, false, false, false}, // #604
    {true, false, false, false, true, false, false, false, false, false}, // #605
    {false, false, true, false, false, true, false, false, false, false}, // #606
    {true, false, false, false, true, false, false, false, false, false}, // #607
    {false, true, false, false, true, true, false, false, false, false}, // #608
    {false, false, true, false, false, false, true, false, false, false}, // #609
    {true, false, false, false, true, false, false, false, false, false}, // #610
    {false, true, false, false, true, true, false, false, false, false}, // #611
    {false, false, true, false, false, true, false, false, false, false}, // #612
    {true, false, false, false, true, false, false, false, false, false}, // #613
    {false, false, true, false, false, true, false, false, false, false}, // #614
    {false, false, false, true, false, false, false, false, false, false}, // #615
    {true, false, false, false, true, false, false, false, false, false}, // #616
    {false, false, true, false, false, false, false, true, false, false}, // #617
    {false, false, false, true, false, false, false, false, false, false}, // #618
    {true, false, false, false, true, false, false, false, false, false}, // #619
    {false, false, true, false, false, true, false, false, false, false}, // #620
    {false, false, false, true, false, false, false, false, false, false}, // #621
    {true, false, false, false, true, false, false, false, false, false}, // #622
    {false, false, true, false, false, true, false, false, false, false}, // #623
    {true, false, false, false, true, false, false, false, false, false}, // #624
    {false, true, false, false, true, true, false, false, false, false}, // #625
    {false, false, false, true, false, false, false, false, false, false}, // #626
    {true, false, false, false, true, false, false, false, false, false}, // #627
    {false, false, true, false, false, true, false, false, false, false}, // #628
    {true, false, false, false, true, false, false, false, false, false}, // #629
    {false, false, true, false, false, true, false, false, false, false}, // #630
    {false, false, false, true, false, false, false, false, false, false}, // #631
    {false, false, false, true, false, false, false, false, false, false}, // #632
    {true, false, false, false, true, false, false, false, false, false}, // #633
    {false, true, false, false, true, true, false, false, false, false}, // #634
    {false, false, true, false, false, true, false, false, false, false}, // #635
    {true, false, false, false, true, false, false, false, false, false}, // #636
    {false, false, true, false, false, true, false, false, false, false}, // #637
    {false, false, false, true, false, false, false, false, false, false}, // #638
    {false, false, false, true, false, false, false, false, false, false}, // #639
    {false, false, false, true, false, false, false, false, false, false}, // #640
    {false, false, false, true, false, false, false, false, false, false}, // #641
    {false, false, false, true, false, false, false, false, false, false}, // #642
    {false, false, false, true, false, false, false, false, false, false}, // #643
    {false, false, false, true, false, false, false, false, false, false}, // #644
    {false, false, false, true, false, false, false, false, false, false}, // #645
    {false, false, false, true, false, false, false, false, false, false}, // #646
    {false, false, false, true, false, false, false, false, false, false}, // #647
    {false, false, false, true, false, false, false, false, false, false}, // #648
    {false, false, false, true, false, false, false, false, false, false}, // #649
    {true, false, false, false, true, false, false, false, false, false}, // #650
    {false, true, false, false, true, true, false, false, false, false}, // #651
    {false, false, true, false, false, true, false, false, false, false}, // #652
    {true, false, false, false, true, false, false, false, false, false}, // #653
    {false, true, false, false, true, true, false, false, false, false}, // #654
    {false, false, true, false, false, true, false, false, false, false}, // #655
    {true, false, false, false, true, false, false, false, false, false}, // #656
    {false, true, false, false, true, true, false, false, false, false}, // #657
    {false, false, true, false, false, true, false, false, false, false}, // #658
    {true, false, false, false, true, false, false, false, false, false}, // #659
    {false, false, true, false, false, true, false, false, false, false}, // #660
    {true, false, false, false, true, false, false, false, false, false}, // #661
    {false, true, false, false, true, true, false, false, false, false}, // #662
    {false, false, true, false, false, true, false, false, false, false}, // #663
    {true, false, false, false, true, false, false, false, false, false}, // #664
    {false, true, false, false, true, true, false, false, false, false}, // #665
    {false, false, true, false, false, true, false, false, false, false}, // #666
    {true, false, false, false, true, false, false, false, false, false}, // #667
    {false, false, true, false, false, true, false, false, false, false}, // #668
    {true, false, false, false, true, false, false, false, false, false}, // #669
    {false, true, false, false, true, true, false, false, false, false}, // #670
    {false, false, true, false, false, false, true, false, false, false}, // #671
    {true, false, false, false, true, false, false, false, false, false}, // #672
    {false, false, true, false, false, true, false, false, false, false}, // #673
    {true, false, false, false, true, false, false, false, false, false}, // #674
    {false, false, true, false, false, true, false, false, false, false}, // #675
    {false, false, false, true, false, false, false, false, false, false}, // #676
    {true, false, false, false, true, false, false, false, false, false}, // #677
    {false, false, true, false, false, true, false, false, false, false}, // #678
    {true, false, false, false, true, false, false, false, false, false}, // #679
    {false, true, false, false, true, true, false, false, false, false}, // #680
    {false, false, true, false, false, false, true, false, false, false}, // #681
    {true, false, false, false, true, false, false, false, false, false}, // #682
    {false, false, true, false, false, false, true, true, false, false}, // #683
    {true, false, false, false, true, false, false, false, false, false}, // #684
    {false, false, true, false, false, false, true, true, false, false}, // #685
    {true, false, false, false, true, false, false, false, false, false}, // #686
    {false, false, true, false, false, true, false, false, false, false}, // #687
    {true, false, false, false, true, false, false, false, false, false}, // #688
    {false, false, true, false, false, true, false, false, false, false}, // #689
    {true, false, false, false, true, false, false, false, false, false}, // #690
    {false, false, true, false, false, true, false, false, false, false}, // #691
    {true, false, false, false, true, false, false, false, false, false}, // #692
    {false, false, true, false, false, true, false, false, false, false}, // #693
    {true, false, false, false, true, false, false, false, false, false}, // #694
    {false, false, true, false, false, false, true, false, false, false}, // #695
    {true, false, false, false, true, false, false, false, false, false}, // #696
    {false, false, true, false, false, true, false, false, false, false}, // #697
    {true, false, false, false, true, false, false, false, false, false}, // #698
    {false, false, true, false, false, true, false, false, false, false}, // #699
    {false, false, true, false, false, true, false, false, true, false}, // #700
    {false, false, false, true, false, false, false, false, false, false}, // #701
    {false, false, false, true, false, false, false, false, false, false}, // #702
    {false, false, false, true, false, false, false, false, false, false}, // #703
    {true, false, false, false, true, false, false, false, false, false}, // #704
    {false, true, false, false, true, true, false, false, false, false}, // #705
    {false, false, true, false, false, true, false, false, false, false}, // #706
    {false, false, false, true, false, false, false, false, false, false}, // #707
    {true, false, false, false, true, false, false, false, false, false}, // #708
    {false, false, true, false, false, false, false, true, false, false}, // #709
    {true, false, false, false, true, false, false, false, false, false}, // #710
    {false, false, true, false, false, false, false, true, false, false}, // #711
    {true, false, false, false, true, false, false, false, false, false}, // #712
    {false, false, true, false, false, true, false, false, false, false}, // #713
    {true, false, false, false, true, false, false, false, false, false}, // #714
    {false, false, true, false, false, true, false, false, false, false}, // #715
    {false, false, false, true, false, false, false, false, false, false}, // #716
    {false, false, false, true, false, false, false, false, false, false}, // #717
    {false, false, false, true, false, false, false, false, false, false}, // #718
    {false, false, false, true, false, false, false, false, false, false}, // #719
    {false, false, false, true, false, false, false, false, false, false}, // #720
    {false, false, false, true, false, false, false, false, false, false}, // #721
    {true, false, false, false, true, false, false, false, false, false}, // #722
    {false, true, false, false, true, true, false, false, false, false}, // #723
    {false, false, true, false, false, true, false, false, false, false}, // #724
    {true, false, false, false, true, false, false, false, false, false}, // #725
    {false, true, false, false, true, true, false, false, false, false}, // #726
    {false, false, true, false, false, true, false, false, false, false}, // #727
    {true, false, false, false, true, false, false, false, false, false}, // #728
    {false, true, false, false, true, true, false, false, false, false}, // #729
    {false, false, true, false, false, true, false, false, false, false}, // #730
    {true, false, false, false, true, false, false, false, false, false}, // #731
    {false, true, false, false, true, true, false, false, false, false}, // #732
    {false, false, true, false, false, true, false, false, false, false}, // #733
    {true, false, false, false, true, false, false, false, false, false}, // #734
    {false, false, true, false, false, true, false, false, false, false}, // #735
    {true, false, false, false, true, false, false, false, false, false}, // #736
    {false, true, false, false, true, true, false, false, false, false}, // #737
    {false, false, true, false, false, true, true, false, false, false}, // #738
    {true, false, false, false, true, false, false, false, false, false}, // #739
    {false, false, true, false, false, true, true, false, false, false}, // #740
    {false, false, false, true, false, false, false, false, false, false}, // #741
    {true, false, false, false, true, false, false, false, false, false}, // #742
    {false, false, true, false, false, true, false, false, false, false}, // #743
    {true, false, false, false, true, false, false, false, false, false}, // #744
    {false, false, true, false, false, true, false, false, false, false}, // #745
    {false, false, false, true, false, false, false, false, false, false}, // #746
    {true, false, false, false, true, false, false, false, false, false}, // #747
    {false, false, true, false, false, true, false, false, false, false}, // #748
    {true, false, false, false, true, false, false, false, false, false}, // #749
    {false, false, true, false, false, true, false, false, false, false}, // #750
    {true, false, false, false, true, false, false, false, false, false}, // #751
    {false, false, true, false, false, true, false, false, false, false}, // #752
    {true, false, false, false, true, false, false, false, false, false}, // #753
    {false, false, true, false, false, true, false, false, false, false}, // #754
    {true, false, false, false, true, false, false, false, false, false}, // #755
    {false, false, true, false, false, true, false, false, false, false}, // #756
    {true, false, false, false, true, false, false, false, false, false}, // #757
    {false, false, true, false, false, true, false, false, false, false}, // #758
    {true, false, false, false, true, false, false, false, false, false}, // #759
    {false, false, true, false, false, true, false, false, false, false}, // #760
    {true, false, false, false, true, false, false, false, false, false}, // #761
    {false, true, false, false, true, true, false, false, false, false}, // #762
    {false, false, true, false, false, true, false, false, false, false}, // #763
    {false, false, false, true, false, false, false, false, false, false}, // #764
    {false, false, false, true, false, false, false, false, false, false}, // #765
    {false, false, false, true, false, false, false, false, false, false}, // #766
    {true, false, false, false, true, false, false, false, false, false}, // #767
    {false, false, true, false, false, true, false, false, false, false}, // #768
    {true, false, false, false, true, false, false, false, false, false}, // #769
    {false, false, true, false, false, true, false, false, false, false}, // #770
    {false, false, false, true, false, false, false, false, false, false}, // #771
    {true, false, false, false, true, false, false, false, false, false}, // #772
    {false, false, true, false, false, true, false, false, true, false}, // #773
    {false, false, false, true, false, false, false, false, false, false}, // #774
    {false, false, false, true, false, false, false, false, false, false}, // #775
    {false, false, false, true, false, false, false, false, false, false}, // #776
    {false, false, false, true, false, false, false, false, false, false}, // #777
    {false, false, false, true, false, false, false, false, false, false}, // #778
    {false, false, false, true, false, false, false, false, false, false}, // #779
    {false, false, false, true, false, false, false, false, false, false}, // #780
    {false, false, false, true, false, false, false, false, false, false}, // #781
    {true, false, false, false, true, false, false, false, false, false}, // #782
    {false, true, false, false, true, true, false, false, false, false}, // #783
    {false, false, true, false, false, true, false, false, false, false}, // #784
    {false, false, false, true, false, false, false, false, false, false}, // #785
    {false, false, false, true, false, false, false, false, false, false}, // #786
    {false, false, false, true, false, false, false, false, false, false}, // #787
    {false, false, false, true, false, false, false, false, false, false}, // #788
    {true, false, false, false, true, false, false, false, false, false}, // #789
    {false, true, false, false, true, true, false, false, false, true}, // #790
    {false, false, true, false, false, true, false, false, false, false}, // #791
    {false, false, true, false, false, true, false, false, false, false}, // #792
    {false, false, false, true, false, false, false, false, false, false}, // #793
    {false, false, false, true, false, false, false, false, false, false}, // #794
    {false, false, false, true, false, false, false, false, false, false}, // #795
    {false, false, false, true, false, false, false, false, false, false}, // #796
    {false, false, false, true, false, false, false, false, false, false}, // #797
    {false, false, false, true, false, false, false, false, false, false}, // #798
    {false, false, false, true, false, false, false, false, false, false}, // #799
    {false, false, false, true, false, false, false, false, false, false}, // #800
    {false, false, false, true, false, false, false, false, false, false}, // #801
    {false, false, false, true, false, false, false, false, false, false}, // #802
    {true, false, false, false, true, false, false, false, false, false}, // #803
    {false, false, true, false, false, true, false, false, false, false}, // #804
    {false, false, false, true, false, false, false, false, false, false}, // #805
    {false, false, false, true, false, false, false, false, false, false}, // #806
    {false, false, false, true, false, false, false, false, false, false}, // #807
    {false, false, false, true, false, false, false, false, false, false}, // #808
    {false, false, false, true, false, false, false, false, false, false}, // #809
    {true, false, false, false, true, false, false, false, false, false}, // #810
    {false, true, false, false, true, true, false, false, false, false}, // #811
    {false, false, true, false, false, true, false, false, false, false}, // #812
    {true, false, false, false, true, false, false, false, false, false}, // #813
    {false, true, false, false, true, true, false, false, false, false}, // #814
    {false, false, true, false, false, true, false, false, false, false}, // #815
    {true, false, false, false, true, false, false, false, false, false}, // #816
    {false, true, false, false, true, true, false, false, false, false}, // #817
    {false, false, true, false, false, true, false, false, false, false}, // #818
    {true, false, false, false, true, false, false, false, false, false}, // #819
    {false, false, true, false, false, true, false, false, false, false}, // #820
    {true, false, false, false, true, false, false, false, false, false}, // #821
    {false, true, false, false, true, true, false, false, false, false}, // #822
    {false, false, true, false, false, true, false, false, false, false}, // #823
    {true, false, false, false, true, false, false, false, false, false}, // #824
    {false, true, false, false, true, true, false, false, false, false}, // #825
    {false, false, true, false, false, true, false, false, false, false}, // #826
    {true, false, false, false, true, false, false, false, false, false}, // #827
    {false, false, true, false, false, true, false, false, false, false}, // #828
    {true, false, false, false, true, false, false, false, false, false}, // #829
    {false, false, true, false, false, true, false, false, false, false}, // #830
    {true, false, false, false, true, false, false, false, false, false}, // #831
    {false, false, true, false, false, true, false, false, false, false}, // #832
    {true, false, false, false, true, false, false, false, false, false}, // #833
    {false, false, true, false, false, true, false, false, false, false}, // #834
    {true, false, false, false, true, false, false, false, false, false}, // #835
    {false, false, true, false, false, true, false, false, false, false}, // #836
    {true, false, false, false, true, false, false, false, false, false}, // #837
    {false, true, false, false, true, true, false, false, false, false}, // #838
    {false, false, true, false, false, true, false, false, false, false}, // #839
    {true, false, false, false, true, false, false, false, false, true}, // #840
    {false, false, true, false, false, false, true, false, false, false}, // #841
    {false, false, true, false, false, false, true, false, false, false}, // #842
    {true, false, false, false, true, false, false, false, false, false}, // #843
    {false, false, true, false, false, true, false, false, false, false}, // #844
    {false, false, false, true, false, false, false, false, false, false}, // #845
    {true, false, false, false, true, false, false, false, false, false}, // #846
    {false, false, true, false, false, true, false, false, false, false}, // #847
    {true, false, false, false, true, false, false, false, false, false}, // #848
    {false, false, true, false, false, true, false, false, false, false}, // #849
    {true, false, false, false, true, false, false, false, false, false}, // #850
    {false, false, true, false, false, true, false, false, false, false}, // #851
    {true, false, false, false, true, false, false, false, false, false}, // #852
    {false, false, true, false, false, true, false, false, false, false}, // #853
    {true, false, false, false, true, false, false, false, false, false}, // #854
    {false, false, true, false, false, false, true, false, false, false}, // #855
    {true, false, false, false, true, false, false, false, false, false}, // #856
    {false, true, false, false, true, true, false, false, false, false}, // #857
    {false, false, true, false, false, true, false, false, false, false}, // #858
    {true, false, false, false, true, false, false, false, false, false}, // #859
    {false, true, false, false, true, true, false, false, false, false}, // #860
    {false, false, true, false, false, true, false, false, false, false}, // #861
    {false, false, true, false, false, true, false, false, false, false}, // #862
    {false, false, true, false, false, true, false, false, false, false}, // #863
    {false, false, true, false, false, true, false, false, false, false}, // #864
    {false, false, true, false, false, false, false, false, false, false}, // #865
    {false, false, true, false, false, true, false, false, false, false}, // #866
    {false, false, true, false, false, false, false, false, false, false}, // #867
    {true, false, false, false, true, false, false, false, false, false}, // #868
    {false, false, true, false, false, false, false, false, false, false}, // #869
    {false, false, false, true, false, false, false, false, false, false}, // #870
    {false, false, false, true, false, false, false, false, false, false}, // #871
    {true, false, false, false, true, false, false, false, false, false}, // #872
    {false, false, true, false, false, true, false, false, true, false}, // #873
    {false, false, false, true, false, false, false, false, false, false}, // #874
    {false, false, false, true, false, false, false, false, false, false}, // #875
    {false, false, false, true, false, false, false, false, false, false}, // #876
    {false, false, false, true, false, false, false, false, false, false}, // #877
    {true, false, false, false, true, false, false, false, false, false}, // #878
    {false, false, true, false, false, true, false, false, false, false}, // #879
    {false, false, false, true, false, false, false, false, false, false}, // #880
    {false, false, false, true, false, false, false, false, false, false}, // #881
    {false, false, false, true, false, false, false, false, false, false}, // #882
    {false, false, false, true, false, false, false, false, false, false}, // #883
    {true, false, false, false, true, false, false, false, false, false}, // #884
    {true, false, false, false, true, false, false, false, false, false}, // #885
    {false, true, false, false, true, true, false, false, false, false}, // #886
    {false, false, true, false, false, true, false, false, false, false}, // #887
    {false, false, false, true, false, false, false, false, false, false}, // #888
    {false, false, false, true, false, false, false, false, false, false}, // #889
    {false, false, false, true, false, false, false, false, false, false}, // #890
    {true, false, false, false, true, false, false, false, false, false}, // #891
    {false, false, true, false, false, false, true, false, false, false}, // #892
    {false, false, false, true, false, false, false, false, false, false}, // #893
    {false, false, false, true, false, false, false, false, false, false}, // #894
    {false, false, false, true, false, false, false, false, false, false}, // #895
    {false, false, false, true, false, false, false, false, false, false}, // #896
    {false, false, false, true, false, false, false, false, false, false}, // #897
    {false, false, false, true, false, false, false, false, false, false}, // #898
    {false, false, true, false, false, false, false, false, false, false}, // #899
    {false, false, true, false, false, false, true, false, false, false}, // #900
    {false, false, true, false, false, false, true, false, false, false}, // #901
    {false, false, true, false, false, false, false, false, false, false}, // #902
    {false, false, true, false, false, true, true, false, false, false}, // #903
    {false, false, true, false, false, true, false, false, false, false}, // #904
    {false, false, false, true, false, false, false, false, false, false}, // #905
    {true, false, false, false, true, false, false, false, false, false}, // #906
    {false, true, false, false, true, true, false, false, false, false}, // #907
    {false, false, true, false, false, true, false, false, false, false}, // #908
    {true, false, false, false, true, false, false, false, false, false}, // #909
    {false, true, false, false, true, true, false, false, false, false}, // #910
    {false, false, true, false, false, true, false, false, false, false}, // #911
    {true, false, false, false, true, false, false, false, false, false}, // #912
    {false, true, false, false, true, true, false, false, false, false}, // #913
    {false, false, true, false, false, true, false, false, false, false}, // #914
    {true, false, false, false, true, false, false, false, false, false}, // #915
    {false, false, true, false, false, true, false, false, false, false}, // #916
    {true, false, false, false, true, false, false, false, false, false}, // #917
    {false, false, true, false, false, true, false, false, false, false}, // #918
    {true, false, false, false, true, false, false, false, false, false}, // #919
    {false, false, true, false, false, true, false, false, false, false}, // #920
    {true, false, false, false, true, false, false, false, false, false}, // #921
    {false, true, false, false, true, true, false, false, false, false}, // #922
    {false, false, true, false, false, true, false, false, false, false}, // #923
    {true, false, false, false, true, false, false, false, false, false}, // #924
    {false, false, true, false, false, false, false, false, false, false}, // #925
    {true, false, false, false, true, false, false, false, false, false}, // #926
    {false, false, true, false, false, true, false, false, false, false}, // #927
    {true, false, false, false, true, false, false, false, false, false}, // #928
    {false, true, false, false, true, true, false, false, false, false}, // #929
    {false, false, true, false, false, true, false, false, false, false}, // #930
    {false, false, false, true, false, false, false, false, false, false}, // #931
    {true, false, false, false, true, false, false, false, false, false}, // #932
    {false, true, false, false, true, true, false, false, false, false}, // #933
    {false, false, true, false, false, true, false, false, false, false}, // #934
    {true, false, false, false, true, false, false, false, false, true}, // #935
    {false, false, true, false, false, false, true, false, false, false}, // #936
    {false, false, true, false, false, false, true, false, false, false}, // #937
    {true, false, false, false, true, false, false, false, false, false}, // #938
    {false, false, true, false, false, false, true, false, false, false}, // #939
    {true, false, false, false, true, false, false, false, false, false}, // #940
    {false, false, true, false, false, true, false, false, false, false}, // #941
    {true, false, false, false, true, false, false, false, false, false}, // #942
    {false, false, true, false, false, true, false, false, false, false}, // #943
    {true, false, false, false, true, false, false, false, false, false}, // #944
    {false, false, true, false, false, true, false, false, false, false}, // #945
    {true, false, false, false, true, false, false, false, false, false}, // #946
    {false, false, true, false, false, true, false, false, false, false}, // #947
    {true, false, false, false, true, false, false, false, false, false}, // #948
    {false, false, true, false, false, true, false, false, false, false}, // #949
    {false, false, false, true, false, false, false, false, false, false}, // #950
    {true, false, false, false, true, false, false, false, false, false}, // #951
    {false, false, true, false, false, false, true, false, false, false}, // #952
    {true, false, false, false, true, false, false, false, false, false}, // #953
    {false, false, true, false, false, true, false, false, false, false}, // #954
    {true, false, false, false, true, false, false, false, false, false}, // #955
    {false, false, true, false, false, true, false, false, false, false}, // #956
    {true, false, false, false, true, false, false, false, false, false}, // #957
    {false, true, false, false, true, true, false, false, false, false}, // #958
    {false, false, true, false, false, true, false, false, false, false}, // #959
    {true, false, false, false, true, false, false, false, false, false}, // #960
    {false, false, true, false, false, true, false, false, false, false}, // #961
    {false, false, false, true, false, false, false, false, false, false}, // #962
    {true, false, false, false, true, false, false, false, false, false}, // #963
    {false, false, true, false, false, true, false, false, false, false}, // #964
    {true, false, false, false, true, false, false, false, false, false}, // #965
    {false, false, true, false, false, true, false, false, false, false}, // #966
    {false, false, false, true, false, false, false, false, false, false}, // #967
    {false, false, false, true, false, false, false, false, false, false}, // #968
    {true, false, false, false, true, false, false, false, false, false}, // #969
    {false, false, true, false, false, true, false, false, false, false}, // #970
    {true, false, false, false, true, false, false, false, false, false}, // #971
    {false, false, true, false, false, true, false, false, false, false}, // #972
    {false, false, false, true, false, false, false, false, false, false}, // #973
    {true, false, false, false, true, false, false, false, false, false}, // #974
    {false, false, true, false, false, false, true, false, false, false}, // #975
    {false, false, false, true, false, false, false, false, false, false}, // #976
    {false, false, false, true, false, false, false, false, false, false}, // #977
    {false, false, false, true, false, false, false, false, false, false}, // #978
    {false, false, true, false, false, false, false, false, false, false}, // #979
    {false, false, true, false, false, true, false, false, false, false}, // #980
    {false, false, true, false, false, true, false, false, false, false}, // #981
    {false, false, true, false, false, true, false, false, false, false}, // #982
    {false, false, true, false, false, false, false, false, false, false}, // #983
    {false, false, false, true, false, false, false, false, false, false}, // #984
    {false, false, false, true, false, false, false, false, false, false}, // #985
    {false, false, false, true, false, false, false, false, false, false}, // #986
    {false, false, false, true, false, false, false, false, false, false}, // #987
    {false, false, false, true, false, false, false, false, false, false}, // #988
    {false, false, false, true, false, false, false, false, false, false}, // #989
    {false, false, false, true, false, false, false, false, false, false}, // #990
    {false, false, false, true, false, false, false, false, false, false}, // #991
    {false, false, false, true, false, false, false, false, false, false}, // #992
    {false, false, false, true, false, false, false, false, false, false}, // #993
    {false, false, false, true, false, false, false, false, false, false}, // #994
    {false, false, false, true, false, false, false, false, false, false}, // #995
    {true, false, false, false, true, false, false, false, false, false}, // #996
    {false, true, false, false, true, true, false, false, false, false}, // #997
    {false, false, true, false, false, true, false, false, false, false}, // #998
    {true, false, false, false, true, false, false, false, false, false}, // #999
    {false, false, true, false, false, false, false, false, false, false}, // #1000
    {false, false, false, true, false, false, false, false, false, false}, // #1001
    {false, false, false, true, false, false, false, false, false, false}, // #1002
    {false, false, false, true, false, false, false, false, false, false}, // #1003
    {false, false, false, true, false, false, false, false, false, false}, // #1004
    {false, false, false, true, false, false, false, false, false, false}, // #1005
    {false, false, false, true, false, false, false, false, false, false}, // #1006
    {false, false, false, true, false, false, false, false, false, false}, // #1007
    {false, false, false, true, false, false, false, false, false, false}, // #1008
    {false, false, false, true, false, false, false, false, false, false}, // #1009
    {false, false, false, true, false, false, false, false, false, false}, // #1010
    {false, true, false, false, true, false, true, false, false, false}, // #1011
    {true, false, false, false, true, false, false, false, false, false}, // #1012
    {false, false, true, false, false, false, true, false, false, false}, // #1013
    {false, false, false, true, false, false, false, false, false, false}, // #1014
    {false, false, false, true, false, false, false, false, false, false}, // #1015
    {false, false, false, true, false, false, false, false, false, false}, // #1016
    {false, false, false, true, false, false, false, false, false, false}, // #1017
    {false, false, true, false, false, false, true, false, false, false}, // #1018
    {false, false, true, false, false, true, false, false, false, false}, // #1019
    {false, false, false, true, false, false, false, false, false, false}, // #1020
    {false, false, false, true, false, false, false, false, false, false}, // #1021
    {false, false, false, true, false, false, false, false, false, false}, // #1022
    {false, false, false, true, false, false, false, false, false, false}, // #1023
    {false, false, false, true, false, false, false, false, false, false}, // #1024
    {false, false, false, true, false, false, false, false, false, false}, // #1025
};

static constexpr int EVOLUTION_SPECIES_COUNT = 1025;
